version: "2.4"
services:
  osm-tools:
    network_mode: host
    image: registry.gitlab.com/gis-ops/swisstopo/kadas-routing-server/kadas-routing-osm-updater
    volumes:
      - ./osmosis_config:/osm_updater/osmosis_config  # necessary
      - ./polys:/osm_updater/polys
      - ./styles:/osm_updater/styles
      - ./osm:/osm_updater/osm
      - /mnt/volume_fra1_02/tmp:/osm_updater/tmp
    environment:
      - OSM_DB=test
      - OSM_POLY=liechtenstein.poly
      - OSM_FILE=liechtenstein-latest.osm.pbf
      - TAG_SET=routing.style
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=gisops
      - POSTGRES_PASS=rocks
      - POSTGRES_PORT=5432
