version: "2.4"
services:
  osm-tools:
    network_mode: host
    image: swisstopo/kadas-routing-osm-tools:test
    container_name: osm-tools
    volumes:
      - ./state.txt:/osm_updater/osmosis/state.txt
      - /mnt/volume_fra1_02/tmp:/osm_updater/tmp
      - ./osm:/osm_updater/osm
    environment:
      - OSM_DB=test
      - OSM_FILE=liechtenstein-latest.osm.pbf
      - TAG_SET=routing.style
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=gisops
      - POSTGRES_PASS=rocks
      - POSTGRES_PORT=5432
