version: "2.4"
services:
  osm-tools:
    network_mode: host
    container_name: osm-tools
    image: registry.gitlab.com/gis-ops/swisstopo/kadas-routing-server/kadas-routing-osm-updater
    volumes:
      - ./osmosis_config:/osm_updater/osmosis_config  # necessary
      - ./polys:/osm_updater/polys
      - ./styles:/osm_updater/styles
      - ./osm:/osm_updater/osm
      - /mnt/volume_fra1_02/tmp:/osm_updater/tmp
    environment:
      - OSM_DB=test
      - OSM_POLY=liechtenstein.poly
      - OSM_FILE=liechtenstein-latest.osm.pbf
      - TAG_SET=routing.style
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=gisops
      - POSTGRES_PASS=rocks
      - POSTGRES_PORT=5432
  db:
    container_name: postgis
    image: postgis:12.0
    volumes:
      - /mnt/volume_fra1_02/data/pg:/var/lib/postgresql
#      - dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=osm,test
      - POSTGRES_USER=gisops
      - POSTGRES_PASS=rocks
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
